### PR TITLE
add debian support for lighty-rnc application

### PR DESCRIPTION
**Pull request by marchest**
add debian support for lighty-rnc application
Signed-off-by: furkan.kaya <kayafurkn@outlook.com>

### CODE REVIEW

**Comment by marchest** [comment]
Hi @ihrasko,

Can you please retrigger the pipeline?. It was getting an error because of minikube version

**Comment by ihrasko** [comment]
@marchest Is it necessary to add this debian docker into lighty repository? IMHO it would be better if you create your own project to create debian based lighty image.

Then you will have full control of your image. And we will not need to maintain this code (debian versions etc).
I would be simpler for both of us. What is your opinion?

**Comment by ihrasko** [comment]
@marchest you have to rebase if you would like to apply latest minikube version bump :)

**Comment by marchest** [comment]
> @marchest Is it necessary to add this debian docker into lighty repository? IMHO it would be better if you create your own project to create debian based lighty image.
> 
> Then you will have full control of your image. And we will not need to maintain this code (debian versions etc). I would be simpler for both of us. What is your opinion?

Debian based docker images are stronger in terms of security and relatively straightforward to make software clearing process according to alpine. I wanted to make contribution for the one who concern this topics, IMHO it would be nice if lighty has support such kind of feature. What do you think?

**Comment by marchest** [comment]
> @marchest you have to rebase if you would like to apply latest minikube version bump :)

@ihrasko thanks, I am going to handle it :)

**Pull request closed without merging**
